version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "prettier"
<<<<<<< HEAD
enabled = true
=======
enabled = true
>>>>>>> adf27702039cb49602f855332c6ce4c37dac2bdb
