version: '3.6'
services:
  kusama:
    image: parity/polkadot:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_ksmcc2:/data/chains
    ports:
      - "127.0.0.1:9933:9933"
      - "0.0.0.0:9944:9944"
      - "127.0.0.1:30333:30333"
    command: ['--chain','kusama','--name', 'KodaDot','--out-peers','20','--in-peers','20','--ws-external','--rpc-external','--rpc-cors','all', '--wasm-execution=Compiled' ]
  kodadot:
    image: yangwao/kodadot:develop-latest
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    ports:
      - "0.0.0.0:8080:8080"

