version: '3.7'

services:
  frontend:
    container_name: Kodadot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/kodadot-app'
      - '/kodadot-app/node_modules'
    ports:
      - '0.0.0.0:9090:9090'
    environment:
      - CHOKIDAR_USEPOLLING=true
