name: Lint, Build & Test workflow

on:
  workflow_dispatch:
    push:
      branches: [main]
  pull_request:
    branches: [main, beta, hyper-jpeg]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Run Test
        run: pnpm test

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Run Build
        run: pnpm generate
