name: Lint, Build & Test workflow

on:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Code Lint
        run: pnpm lint:quiet

      - name: Run Build
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-12'
        run: pnpm generate

      # remove continue-on-error when https://github.com/paritytech/smoldot/issues/2564 resolved
      - name: Run Build on Windows
        if: matrix.os == 'windows-latest'
        continue-on-error: true
        run: pnpm generate

      - name: Run Test
        run: pnpm test
