name: Lint, Build & Test workflow

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: node-linker=hoisted

      - run: cat .npmrc

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest
          run_install: true

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Run Code Lint
        run: pnpm lint:quiet

      - name: Run Build
        run: pnpm build

      - name: Run Test
        run: pnpm test
