name: Cypress tests

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
      - name: Test
        run: |
          pnpm test:e2e
      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-website-screenshots
          path: /tests/cypress/screenshots/

