name: Create diagram
on:
   schedule:
# “At 00:42 on Monday.”
   - cron: '42 0 * * 1'  
#  best would be add [skip ci] to commit message, this schedule is tmp workaround
#  workflow_dispatch: {}
#  push:
#    branches:
#      - main-nuxt
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          commit_message: "[skip ci] KodaDot: updated diagram"
