name: cypress

on:
  workflow_dispatch:
    push:
      branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:10.10.0
      options: --user 1001
    env:
      CYPRESS_CACHE_FOLDER: '${GITHUB_WORKSPACE}/.cypress-cache'
    strategy:
      matrix:
        index: [1, 2, 3, 4] # [1, ..., n] where n === parallelSize in e2e-run-tests.js
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install && pnpm cypress install

      - name: Download artifact
        id: artifact
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          pr: ${{ github.event.pull_request.number }}
          name: ubuntu-latest-artifact

      - name: Build App
        if: steps.artifact.outcome == 'failure'
        run: pnpm generate

      - name: Cypress run
        run: pnpm start:static & pnpm wait-on http://localhost:9090 && MATRIX=${{ matrix.index }} node tests/cypress/e2e-run-tests.js

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: ./cypress/screenshots/
